Bug 1880015 - Remove some unused chromium/base/strings functions to fix C++20 build. r=bobowen
Attempting to compile security/sandbox with -std=c++20 hits this build error:

> security/sandbox/chromium/base/strings/string_util.cc:1043:53: error: overload resolution selected deleted operator '<<'
> |             DLOG(ERROR) << "Invalid placeholder: $" << *i;

This error is caused because C++20 removed basic_string's `operator<<` overloads for char types because the overloads didn't behave as callers expected: instead of printing the character value ('A'), they treated the char as an integer value (65):

https://en.cppreference.com/w/cpp/io/basic_ostream/operator_ltlt2

mozilla-central's security/sandbox code doesn't actually use these `ReplaceStringPlaceholders` functions, so just remove them instead of cherry picking Chromium's upstream fix.

Differential Revision: https://phabricator.services.mozilla.com/D201675

UltraBlame original commit: 6406a92f4a33def5a8efdfcdde232b828c4d5f90