Bug 1888181 - Vendor libwebrtc from 1b52d5641e
Upstream commit: https://webrtc.googlesource.com/src/+/1b52d5641e062bf56f1f7b40fd980b8b9e9f2679
    Fix generate_buildbot_json and switch to ios_runtime_cache_17_4.

    When running it, even without changes at HEAD I got:

    ```
    KeyError: 'ios_runtime_cache_17_0'
    ```

    Bug: b/325441006
    Change-Id: I7ea236ccc1f7439d7750208260b01d7636db4ae5
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/339842
    Commit-Queue: Mirko Bonadei <mbonadeiwebrtc.org>
    Reviewed-by: Jeremy Leconte <jlecontegoogle.com>
    Cr-Commit-Position: refs/heads/main{#41751}

UltraBlame original commit: c6dedd2c379a0368d1ef40f43b8f8473fddacd63