Bug 1888181 - Vendor libwebrtc from c0741e9f12
We already cherry-picked this when we vendored 59f3b35013.

Upstream commit: https://webrtc.googlesource.com/src/+/c0741e9f12df679a2ec634d064edd212d7e72ed3
    Revert "Take out Fuchsia-only SDES-enabling parameters"

    This reverts commit 59f3b35013a29f8c73a46fa6fd06aadc96aad892.

    Broke WebRTC into Chrome rolls:

    https://chromium-review.googlesource.com/c/chromium/src/+/5248171?tab=checks

    /../third_party/blink/renderer/modules/peerconnection/rtc_peer_connection_handler.cc:216:18: error: no member named 'enable_dtls_srtp' in 'webrtc::PeerConnectionInterface::RTCConfiguration'
      216 |   configuration->enable_dtls_srtp = dtls_srtp_key_agreement;
          |   ~~~~~~~~~~~~~  ^

    Original change's description:
    > Take out Fuchsia-only SDES-enabling parameters
    >
    > This does not remove all traces of SDES - we still need to delete
    > the cricket::CryptoParams struct and all code that uses it.
    >
    > Bug: webrtc:11066, chromium:804275
    > Change-Id: I811c8d40da7f4af714d53376f24cd53332a15945
    > Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/336780
    > Reviewed-by: Henrik Boström <hboswebrtc.org>
    > Commit-Queue: Harald Alvestrand <htawebrtc.org>
    > Cr-Commit-Position: refs/heads/main{#41634}

    Bug: webrtc:11066, chromium:804275
    Change-Id: I2c2114873091e0c662977a6ef5723e6447166a65
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/337181
    Commit-Queue: Olga Sharonova <olkawebrtc.org>
    Reviewed-by: Henrik Boström <hboswebrtc.org>
    Bot-Commit: rubber-stamperappspot.gserviceaccount.com <rubber-stamperappspot.gserviceaccount.com>
    Owners-Override: Olga Sharonova <olkawebrtc.org>
    Cr-Commit-Position: refs/heads/main{#41643}

UltraBlame original commit: dc46285144cdba79c187bc978dfe6f5489fe5fdc