Bug 1925698 [wpt PR 48709] - Fix Safari artifact names, a=testonly
Automatic update from web-platform-tests
Fix Safari artifact names

With the unified workflow, we don't actually need to specify the
wildcard, as this will just lead to errors like:

> Error: The artifact name is not valid:
> safari-technology-preview-results-*-6. Contains the following
> character: Asterisk *

e.g., in
https://github.com/web-platform-tests/wpt/actions/runs/11410328782/job/31752427266

--

wpt-commits: c7805fef3ca1b6e840fb57315be2edf4a271c853
wpt-pr: 48709

UltraBlame original commit: 6734152e0da78b5359167423bfbdda2a2b297eb0