Bug 1041962 - Include libgen.h for basename r=jseward
Currently, the GNU version of basename from string.h is used, which
has behavior that conflicts with the POSIX version in libgen.h.

The GNU basename is not available in all libcs. In particular, it
is missing in musl libc, causing a build failure:

	error: 'basename' was not declared in this scope

The GNU version has the following implementation:

	char *p = strrchr (filename, '/');
	return p ? p + 1 : (char *) filename;

The POSIX version has slightly different semantics. It may modify
its argument string, or copy part of it to static storage. However,
it will also delete trailing slashes, while the GNU version will
return the empty string if there is a trailing slash.

This change resolves the issue by including libgen.h, adopting POSIX
basename semantics. This should be a safe change for the following
reasons:

- The google-breakpad code, from which this code was derived, has
  also switched to the POSIX basename:
  https://chromium.googlesource.com/breakpad/breakpad/+/072f86ca83bb7138fe33f10b6380badd9ef7f065%5E%21/#F4

- The version of LulElf.cpp in mozglue/baseprofiler has also switched
  to the POSIX basename:
  https://hg.mozilla.org/mozilla-central/annotate/de1c3ae8df14cdb2c94a817b02dcffcb2cee12e2/mozglue/baseprofiler/lul/LulElf.cpp#l54

- The BaseFileName function is called only with paths to ELF files,
  never directories, so the paths will never contain a trailing
  slash, and the two versions of basename will behave identically.

Differential Revision: https://phabricator.services.mozilla.com/D61047

UltraBlame original commit: a3096ca24124886f8642cb45d2091af0cc4010e1