Bug 1304176 - Use vendored virtualenv if available; r=ted
If mozharness is running from a source checkout, it has access to a
modern virtualenv+pip/setuptools vendored as part of the source
checkout.

This commit changes the virtualenv creation code to use the vendored
virtualenv when it is available.

A side effect of this change is that a modern version of pip will
now be used by mozharness when a source checkout is available. This
has a number of consequences.

First, modern versions of pip automatically create and cache wheels
when building packages. This should make automation faster since it can
now reuse cached wheels instead of having to download and rebuild
packages all the time.

Second, modern versions of pip support pinning package hashes. This
opens the door to use having more secure package downloads and more
determinism in our test environment.

Third, modern versions of pip require connections to package servers
be secure by default. Plaintext connections are disallowed by
default. A --trusted-host option or environment variable can be used
to override this behavior.

Since upgrading pip resulted in some jobs failing due to disallowed
connections to insecure servers, code to sniff the pip version and
add --trusted-host where it is needed/supported. This retains the
existing behavior. This is insecure. But fixing that is for another
bug.

As part of testing this, we were getting IOError inside virtualenv.py
when installing distutils:

IOError: [Errno 13] Permission denied: '/builds/slave/test/build/venv/lib/python2.7/distutils/__init__.py'

We worked around this by adding --always-copy to the virtualenv.py
invocation.

MozReview-Commit-ID: D29ao9ZASei

UltraBlame original commit: 3fd83c9c0548b3f07c844a2f6c3a23ae7569eecd