Bug 1164658 - disable test_web_channel.js for thunderbird, as it requires weave which thunderbird doesn't have. r=markh
TEST-UNEXPECTED-FAIL | services/fxaccounts/tests/xpcshell/test_web_channel.js | xpcshell return code: 0
TypeError: Cc['mozilla.org/weave/service;1'] is undefined at resource://gre/modules/FxAccountsWebChannel.jsm:227

UltraBlame original commit: 461be7d30fda2cb8889349aa426e121d4e466f47