Bug 2069686 - uniffi: Move PromiseHandler's destructor out of line for C++23 compatibility. r=nika
C++23 P2448R2 [1] relaxed the requirements for constexpr destructors.
C++23 makes UniquePtr's destructor, move constructor, and null
assignment operator automatically constexpr.

Clang defines PromiseHandler's virtual destructor inline when the
enclosing AsyncCallbackMethodHandlerBase class is still incomplete.
This instantiates the destruction path for
UniquePtr<AsyncCallbackMethodHandlerBase>, whose default deleter
requires AsyncCallbackMethodHandlerBase to be complete.

To resolve this, move PromiseHandler's destructor definition to
Callbacks.cpp where AsyncCallbackMethodHandlerBase is complete.

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2448r2.html

MacOSX26.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:75:19: error: invalid application of 'sizeof' to an incomplete type 'mozilla::uniffi::AsyncCallbackMethodHandlerBase'
75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
   |                   ^~~~~~~~~~~
toolkit/components/uniffi-js/Callbacks.h:137:5: note: in instantiation of member function 'std::unique_ptr<mozilla::uniffi::AsyncCallbackMethodHandlerBase>::~unique_ptr' requested here
137 |     ~PromiseHandler() = default;
    |     ^
toolkit/components/uniffi-js/Callbacks.h:137:5: note: in defaulted destructor for 'mozilla::uniffi::AsyncCallbackMethodHandlerBase::PromiseHandler' first required here
toolkit/components/uniffi-js/Callbacks.h:75:7: note: definition of 'mozilla::uniffi::AsyncCallbackMethodHandlerBase' is not complete until the closing '}'
75 | class AsyncCallbackMethodHandlerBase {
   |       ^

Differential Revision: https://phabricator.services.mozilla.com/D324858

UltraBlame original commit: 147db67f1ef8b29322ac739798b94bd2a68f5351