servo: Merge #3991 - Update README for Homebrew (from Hoverbear:patch-1); r=jdm
glfw3 is in the `homebrew/versions` keg.

```bash
➜  ~  brew install glfw3
Error: No available formula for glfw3
Searching formulae...
Searching taps...
homebrew/versions/glfw3
```

Simplest fix:

```bash
﻿➜  ~  brew install homebrew/versions/glfw3
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-versions'...
remote: Counting objects: 2495, done.
remote: Total 2495 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2495/2495), 820.05 KiB | 462.00 KiB/s, done.
Resolving deltas: 100% (1433/1433), done.
Checking connectivity... done.
Tapped 161 formulae
==> Installing glfw3 from homebrew/homebrew-versions
==> Downloading https://downloads.sourceforge.net/project/glfw/glfw/3.0.4/glfw-3.0.4.tar.bz2
Already downloaded: /Library/Caches/Homebrew/glfw3-3.0.4.tar.bz2
==> Patching
patching file CMakeLists.txt
Hunk #1 succeeded at 370 with fuzz 1 (offset 13 lines).
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/glfw3/3.0.4 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DGLFW_USE_CHDIR=TRUE -DGLFW_USE_MENUBAR=TRUE -DBUIL
==> make install
🍺  /usr/local/Cellar/glfw3/3.0.4: 11 files, 220K, built in 9 seconds
```

Users who have `homebrew/versions` already tapped won't notice this, since after tapping `homebrew/versions` keg shouldn't notice, since after tapping, the library is available using just ` brew install glfw3`.

```bash
➜  ~  brew tap
homebrew/versions
➜  ~  brew install glfw3
==> Installing glfw3 from homebrew/homebrew-versions
==> Downloading https://downloads.sourceforge.net/project/glfw/glfw/3.0.4/glfw-3.0.4.tar.bz2
Already downloaded: /Library/Caches/Homebrew/glfw3-3.0.4.tar.bz2
==> Patching
patching file CMakeLists.txt
Hunk #1 succeeded at 370 with fuzz 1 (offset 13 lines).
==> cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/glfw3/3.0.4 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DGLFW_USE_CHDIR=TRUE -DGLFW_USE_MENUBAR=TRUE -DBUIL
==> make install
🍺  /usr/local/Cellar/glfw3/3.0.4: 11 files, 220K, built in 9 seconds
```

Source-Repo: https://github.com/servo/servo
Source-Revision: b9dcaa34c32333ae16da7a5f11835c7d905da4d3

UltraBlame original commit: 8739cfacc1ef22e0eae31d22cbdc94bbaefeb4b3