Bug 1846031 [wpt PR 41231] - Fenced frames: Remove FencedFrameConfig constructor in web platform tests., a=testonly
Automatic update from web-platform-tests
Fenced frames: Remove FencedFrameConfig constructor in web platform
tests.

FencedFrameConfig should only be used for developer-only mode. Web
platform tests should not rely on them. Replace the constructors with
functions that use either Protected Audience or Shared Storage to
generate the navigation target.

Note: I used generateURNFromFledge in top-level frame, but change to
runSelectURL in nested frame. I found generateURNFromFledge gives this
error in nested frame:

NotAllowedError: Failed to execute 'joinAdInterestGroup' on 'Navigator': Feature join-ad-interest-group is not enabled by Permissions Policy

Bug: 1420626
Change-Id: I9eab022e0370695c42aca10568a0fc5cdca1cc2f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4727007
Reviewed-by: Dominic Farolino <domchromium.org>
Commit-Queue: Xiaochen Zhou <xiaochenzhchromium.org>
Cr-Commit-Position: refs/heads/main{#1176759}

--

wpt-commits: cec8d856b5ca0d9a3e20eb1a537f4b0c1f1bc9f0
wpt-pr: 41231

UltraBlame original commit: 1aa2d325bbf90008340cb7b1c64eb86e95a5c902