Bumping gaia.json for 2 gaia revision(s) a=gaia-bump
========

https://hg.mozilla.org/integration/gaia-central/rev/5746057ab313
Author: Thomas Zimmermann <tdzusers.sourceforge.net>
Desc: Merge pull request #15907 from tdz/bug-966243

Bug 966243: Fix ICC detection handlers in Settings app

========

https://hg.mozilla.org/integration/gaia-central/rev/aef67c3ac9de
Author: Thomas Zimmermann <tdzusers.sourceforge.net>
Desc: Bug 966243: Fix ICC detection handlers in Settings app, r=arthur.chen

While running the Settings app several errors about self.* not being
defined show up in the logcat. An example is

  E/GeckoConsole(  440): [JavaScript Error: "TypeError: self.updateSimPinsUI \
    is not a function" {file: "app://settings.gaiamobile.org/js/simcard_lock.js" \
    line: 232}]

This is caused by 'self' not being set in the event handlers for ICC
detection. As a result, the UI update does not work correctly when the
ICC changes state. Setting the variable 'self' fixes this problem.

Signed-off-by: Thomas Zimmermann <tdzusers.sourceforge.net>

UltraBlame original commit: ae3a269ac575cb8c7f743db3e4124c12ee971b47